<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Authors>Mochix2Milk</Authors>
    <Company>Mochix2Milk</Company>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
