<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CrossRagfair.Contracts\CrossRagfair.Contracts.csproj" />
    <ProjectReference Include="..\..\src\CrossRagfair.Core\CrossRagfair.Core.csproj" />
    <ProjectReference Include="..\..\src\CrossRagfair.Hub\CrossRagfair.Hub.csproj" />
  </ItemGroup>
</Project>
